# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 563f2b045bf10099f94d44fdd8c211b71ce147ecb0d3de1ffd632660265b13d6a79f031aba3b4eae75ce043e20a3569268934203a6ea2b9fe2cd20386a6489da

test:
  secret_key_base: 361582162f900f274c552ed24eadb10688076a47995990f4f8586e3ed00ef4163e1831f3f02c713269ef01637ed15ad613ce646317989463154eacba02b86ffd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
